# Generated by Django 2.0.13 on 2019-02-22 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190222_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='how',
        ),
        migrations.AddField(
            model_name='skill',
            name='body',
            field=ckeditor.fields.RichTextField(default='null'),
            preserve_default=False,
        ),
    ]
