# Generated by Django 2.0.13 on 2019-03-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='cover',
        ),
    ]
